### ISSUE TITLE
Reloading while a render is ongoing causes massive lag spikes. 

### ISSUE THREAD

**Issue by Maroon28** [BillyGalbreath/Pl3xMap#120]
While an active render is taking place, if the plugin is reloaded at any point, the server hangs _very_ badly. Mine went from ~30 mspt to up to ~560. It stayed like that for about a minute or so before it cooled back down again. Here's a log with an error that was thrown after the reload.

https://pastes.dev/bTZjtFMEpi

**Comment by BillyGalbreath** [comment]
Hmm. Seems it picks up too quickly at resuming the render. I'll have to add a bigger delay to let the old render have time to finish and release the threads.

**Comment by BillyGalbreath** [comment]
Can you test this on v3 to see if it's still a problem?

https://hangar.papermc.io/BillyGalbreath/Pl3xMap

**Comment by BillyGalbreath** [comment]
Closing this, as I'm fairly certain this is not relevant to v3
