### ISSUE TITLE
Error Spamming Console

### ISSUE THREAD

**Issue by MindMasterz** [BillyGalbreath/Pl3xMap#125]
Set up pl3xmap and this error is spamming console at the moment not causing any issues performance wise from what I see could be but thought you should see

https://pastebin.com/H4UvkmsC

**Comment by Olzie-12** [comment]
I do believe this error may be caused from my code, and it was working fine in v1. Am i doing something wrong?https://haste.olziedev.com/biracedovo.kotlin

**Comment by BillyGalbreath** [comment]
Let me know if [build 315](https://modrinth.com/plugin/pl3xmap/version/1.19.2-315) fixes this issue.

**Comment by MindMasterz** [comment]
This did fix the console spam not the issue with olzie which was his playerwarps plugin no longer works on the map but thank you!
