### ISSUE TITLE
[BUG] Incorrect Logic in Option#isDefault

### ISSUE THREAD

**Issue by silverwolfg11** [BillyGalbreath/Pl3xMap#126]
## Summary of Issue:
According to the the javadoc comment for `Option#isDefault` ([jd reference](https://billygalbreath.github.io/Pl3xMap/net/pl3x/map/markers/option/Option.html#isDefault())), the method should return true only if all the properties of that option are null (or default values).

However, in all the implementations I checked, the method returns true when all the properties are not default. 
I'll use Fill as an example option.
```java
   public boolean isDefault() {
        return isEnabled() != null &&
                getType() != null &&
                getColor() != null;
    }
```
This return true if `enabled` is was initialized to a boolean, a type was specified, and a color was specified (meaning all the properties were set).

## Indirect Bugs Caused by This
Trying to use the Options builder results in an incorrect options instance because the builder checks each time if an option is default and if so will set the field to null. Hence, when all properties of an option are set (thus `Option#isDefault` will return true), the option field will be set to null in the builder and not be applied when built.

## Expected Behavior
I expect the method to return true if all the properties of that option are null. I believe the logic should be changed to something like:
```java
   public boolean isDefault() {
        return isEnabled() == null &&
                getType() == null &&
                getColor() == null;
    }
```

**Comment by BillyGalbreath** [comment]
So sorry for the delay in fixing this. :3 It's been a rough last couple months for me IRL.

**Comment by silverwolfg11** [comment]
No worries! Thank you for fixing this and hope things get better soon!
