### ISSUE TITLE
Weird Cords

### ISSUE THREAD

**Issue by Technocality** [BillyGalbreath/Pl3xMap#128]
I was testing and noticed that the Z cords on the web interface were not loading correctly, the block name was also not working. On most blocks, it says x-value, ???,  y-value, however, on some blocks, it says x-value, something like -1108541264,  y-value. I deleted all the files, including the jar, and regenerated them, but the issue persisted.

![image](https://user-images.githubusercontent.com/105610111/201461238-b92cd8a5-f4ba-4f33-b738-365887ad1deb.png)

**Comment by BillyGalbreath** [comment]
This is not a bug, this is a misconfiguration on your part. Join the Discord server for support. https://discord.gg/nhGzEkwXQX
