### ISSUE TITLE
[1.19] Confusion

### ISSUE THREAD

**Issue by MrRagtime** [BillyGalbreath/Pl3xMap#131]
### I can't seem to connect to Pl3xMap on my browser.
I've set my IP in Pl3xMap's config to _public_, _private_, even to _0.0.0.0_ and I still cannot connect.
**I'm using Pterodactyl so could that be the problem?**

**Comment by BillyGalbreath** [comment]
GitHub Issues are not for support requests. Join our Discord for support.
