### ISSUE TITLE
[Feature Request] Show link when player has no perms.

### ISSUE THREAD

**Issue by ZepsiZola** [BillyGalbreath/Pl3xMap#140]
If a player doesn't have any perms to pl3xmap, they should simply be given a configurable message that contains the link to the server map. This would be convenient.

**Comment by BillyGalbreath** [comment]
Yes, all of the subcommand permissions automatically give permission to the base command. So if you give someone `pl3xmap.command.hide` you dont have to give them `pl3xmap.command.map` because they will automatically get it.
