### ISSUE TITLE
Thinking about Folia?

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [BillyGalbreath/Pl3xMap#145]
I see that the squaremap is already adapted to Folia, but I think Pl3xmap does a lot better than the squaremap in some aspects, do you consider adapting Folia?

**Comment by JasperTheMinecraftDev** [comment]
It has a very different API so no.

**Comment by Roan-V** [comment]
https://github.com/PaperMC/Folia#the-new-rules

**Comment by BillyGalbreath** [comment]
> https://github.com/PaperMC/Folia#the-new-rules

Huh, well v3 doesn't use any of the Bukkit API that wouldn't be thread safe already, so it should "just work".

I'll add that to the plugin.yml later tonight and see if anything blows up.

**Comment by JasperTheMinecraftDev** [comment]
Good idea, recommend reading the page first though. There are some things that are entirely broken.

**Comment by BillyGalbreath** [comment]
Had to add in a main tick heartbeat since folia doesnt seem to have one, but preliminary testing of v3 on folia looks good. I dont have a busy server to really test it on, though. Good luck ^_^

Implemented as of [build 349](https://hangar.papermc.io/BillyGalbreath/Pl3xMap) https://github.com/BillyGalbreath/Pl3xMap/commit/f62937d00426dc225adb467e207a3c504550823b

**Comment by xiaoyueyoqwq** [comment]
> Had to add in a main tick heartbeat since folia doesnt seem to have one, but preliminary testing of v3 on folia looks good. I dont have a busy server to really test it on, though. Good luck ^_^
> 
> Implemented as of [build 349](https://hangar.papermc.io/BillyGalbreath/Pl3xMap) [f62937d](https://github.com/BillyGalbreath/Pl3xMap/commit/f62937d00426dc225adb467e207a3c504550823b)

I think you should have the right person - I am the administrator of this kind of server ;)
Well, if there is a problem, I will continue to open an issue to provide feedback, and finally thank you for your dedication to the Folia server
