### ISSUE TITLE
java.lang.IllegalStateException: can't find /locale on the classpath

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [BillyGalbreath/Pl3xMap#146]
This is the err report logs:
-----------------------------------
https://paste.ubuntu.com/p/KK6n9gVSzg/
-----------------------------------
Fix it, and add a update tag ;-)

**Comment by BillyGalbreath** [comment]
I think this has something to do with your server's locale. Be sure it's set to UTF-8 on the OS level, or try with the Java flag.

**Comment by xiaoyueyoqwq** [comment]
> I think this has something to do with your server's locale. Be sure it's set to UTF-8 on the OS level, or try with the Java flag.

I think I should have no problem setting it up, because I used the same settings to load Pl3xmap on the Paper/Purpur server before, and I tried resetting the settings

**Comment by xiaoyueyoqwq** [comment]
> I think this has something to do with your server's locale. Be sure it's set to UTF-8 on the OS level, or try with the Java flag.

No way.. I tried a lot of things but it didn't work, maybe it's a bug

**Comment by galacticwarrior9** [comment]
I'm having this issue too, using Pl3xMap `1.19.4-347` and Purpur `1965` on a fresh installation. Adding `-Dfile.encoding=UTF-8` to the startup flags did not help.

**Comment by galacticwarrior9** [comment]
Seems to be fixed for me as of build 360.

**Comment by BillyGalbreath** [comment]
Sorry, I thought I responded to this ticket asking if it was fixed in build 355.

I'm glad to hear that it is indeed fixed ^_^

**Comment by xiaoyueyoqwq** [comment]
> Sorry, I thought I responded to this ticket asking if it was fixed in build 355.
> 
> I'm glad to hear that it is indeed fixed ^_^

thanks for your help ;)
