### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by ItzSave** [BillyGalbreath/Pl3xMap#150]
Hello, When attempting to boot my server with Pl3xMap-1.19.4-384 installed the console will give the following error on startup.
https://paste.helpch.at/bifofogegu.md

Then after that it will proceed to start spamming the following in console:
`[22:29:15 WARN]: java.lang.ArrayIndexOutOfBoundsException`

The server is running Pufferfish+ 1.19.4 build #54 with the following plugins installed:
- Chunky v1.3.52
- ChunkyBorder v1.1.42
- Multiverse-Core v4.3.2
- Pl3xMap v 1.19.4-394
- ProtocolLib
- Vault
- WorldEdit v7.2.14
- WorldGuard v7.0.8-beta-01

**Comment by BillyGalbreath** [comment]
Wow, how old is your world? I only have chunk readers back to 1.13 formats. I do see that I need to fail more gracefully for these ancient worlds, though.

Anyways, to fix this you're going to have to force upgrade your chunks. Join the discord if you need help, there are plenty of us that can assist.

**Comment by BillyGalbreath** [comment]
Ignore my last response. Seems you chunk versions fall within the acceptable range. I was using the wrong long reader in the older chunk formats, but I've corrected this in build 385. Let me know if that fixes the issue for you.

**Comment by ItzSave** [comment]
This did indeed fix my problem thank you. I forgot that the world I'm using was made in 1.17 so that didn't even cross my mind.
