### ISSUE TITLE
[Issue] Consle spamming an error message.

### ISSUE THREAD

**Issue by ItzSave** [BillyGalbreath/Pl3xMap#151]
When booting my server my console starts spamming this error repeatedly even with a brand new Pl3xMap folder generated with all new config files.

https://paste.helpch.at/irunibezay.md

This is on Pl3xMap-1.19.4-413

**Comment by BillyGalbreath** [comment]
Your world is super old and needs updating. Run it through Chunky as if you were going to pregen it, but make sure you have force load chunks enabled in the chunky config. The act of loading and unloading all your chunks will update them. Then you can run a render over it.

**Comment by ItzSave** [comment]
That seems to of fixed my issue. Thank you!
