### ISSUE TITLE
Map tiles occasionally all vanish until zoom/reload

### ISSUE THREAD

**Issue by Garmelon** [BillyGalbreath/Pl3xMap#153]
When having pl3xmap open in the browser while a player is connected and moving around the world, occasionally all map tiles will vanish. When that happens, zooming (even by just one scroll wheel tick) or reloading the page will make the map tiles reappear.

It doesn't seem like this happens when no player is connected.

When this happens, the browser dev tools show multiple requests for map tiles where the server consistently responds with 0 bytes of content. The only headers set by the server are `Connection: keep-alive`, `Content-length: 0` and `Date: <actual date>`.
![pl3xmap_devtools](https://github.com/BillyGalbreath/Pl3xMap/assets/11077553/db3e039a-214f-4179-b09f-83200a009fb0)

This happens in both Firefox and Chromium. It happens both with nginx proxying the requests, and when connecting directly to the pl3xmap web server.

**Comment by BillyGalbreath** [comment]
Ok, I narrowed down the problem (finally). Tiles seem to disappear when viewing at a non-integer zoom level (anything with a decimal point that's not 0). Since that zoom stuff is rather new, I've decided to revert that change until I can figure out how to make it all work correctly. So, this should be fixed in build 422, because the only zoom level are integers (whole numbers).

**Comment by Garmelon** [comment]
Ah, so that's what that menu is meant to do. It appears to be broken as well on the latest build. I guess I'll open another issue, heh :)

**Comment by BillyGalbreath** [comment]
I have switched back to using atomic move in build 427. Let's see if this helps ^_^

**Comment by Garmelon** [comment]
I've used build 430 for a bit now and never saw a tile disappear.

Following a player and dying worked perfectly too. Thanks a lot for the (very quick) fixes! Pl3xMap is very nice to use and to configure (especially compared to dynmap ^^), updates quickly and runs well even on my lower-end VPS.
