### ISSUE TITLE
Following a player doesn't work

### ISSUE THREAD

**Issue by Garmelon** [BillyGalbreath/Pl3xMap#154]
1. Open the web map while connected the map's server via Minecraft
2. Click on the players tab and select yourself.
3. Move around on the server.

After step 2, nothing happens except the player UI element you just clicked on changing color. I'd expect the map to focus on the player, but it doesn't scroll or move in any way.

During step 3, nothing happens either. I'd expect the map to scroll so the player stays in the middle of the screen, or at least so that the player can't move entirely offscreen.

The browser dev console shows no errors aside from the ones I mentioned in #153. This test was performed with build 423.

**Comment by BillyGalbreath** [comment]
Fixed in build 425 \o/
