### ISSUE TITLE
Dying breaks player position

### ISSUE THREAD

**Issue by Garmelon** [BillyGalbreath/Pl3xMap#158]
After dying, the player who died vanishes from the browser map as expected.

After respawning however, the player is displayed with zero armor and hearts in their spawn location, facing southwards. The player marker in the browser does not rotate nor move when the player does.
![image](https://github.com/BillyGalbreath/Pl3xMap/assets/11077553/1744c364-7fab-4b9e-b9dc-281500e35f07)

Using the `/pl3xmap reload` command fixes this.

This bug occurred with build 423.

**Comment by BillyGalbreath** [comment]
Fixed in build 426 \o/

**Comment by Garmelon** [comment]
I died and respawned multiple times and everything seemed fine. However, toggling the "player" layer off and on again makes ghost player markers appear at the positions where the player died. Should I open a new issue for this?

**Comment by BillyGalbreath** [comment]
> I died and respawned multiple times and everything seemed fine. However, toggling the "player" layer off and on again makes ghost player markers appear at the positions where the player died.

Ok, took me awhile to track this one down, but I finally did ^_^ Should be fixed in build 431

**Comment by Garmelon** [comment]
Appears to be fixed, I couldn't reproduce the bug with the latest build.
