### ISSUE TITLE
Claim add-on causing lag and eventually crash with grief prevention

### ISSUE THREAD

**Issue by matipoirierg** [BillyGalbreath/Pl3xMap#163]
git-Purpur-1990 (MC: 1.20)*
Pl3xMap version 1.20-441
Pl3xMap Claims 1.20-23
https://spark.lucko.me/ckTP2GUleG
Crash error: https://mclo.gs/uMkV8U5
I uninstalled the add-on and the server goes back to normal behavior.

**Comment by BillyGalbreath** [comment]
This is the Pl3xMap repo. You want the [Pl3xMap-Claims](https://github.com/BillyGalbreath/Pl3xMap-Claims) repo. Or could even talk to [GriefPrevention](https://github.com/TechFortress/GriefPrevention) to find out why their API is causing your server to lag out and crash.
