### ISSUE TITLE
Pl3xMap crashing 1.20.1 Mohist server (plugin)

### ISSUE THREAD

**Issue by taswin** [BillyGalbreath/Pl3xMap#171]
Server fails to load Pl3xMap as a plugin. (I realised that Pl3xMap-Banners was only available as a plugin.)

[24Jun2023 18:01:20.769] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Pl3xMap v1.20.1-452 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.core.IdMap

Full log: [https://pastebin.com/rZ4Qqf1c](url)

**Comment by BillyGalbreath** [comment]
Mohist is not supported.
