### ISSUE TITLE
[Enhancement] Hide players on map under conditions

### ISSUE THREAD

**Issue by 42Willow** [BillyGalbreath/Pl3xMap#173]
- [ ] Option to hide players whilst sneaking
- [ ] Option to hide players whilst not visible to the sky

**Comment by BillyGalbreath** [comment]
Sounds like a perfect addon if someone wants to make it.

Here's my initial untested thoughts on how one could possibly implement it:

```java
    @EventHandler
    public void onPlayerMove(PlayerMoveEvent event) {
        if (!getConfig().getBoolean("hide-if-under-blocks")) {
            return; // feature disabled
        }
        Location from = event.getFrom();
        Location to = event.getTo();
        if (from.getWorld().equals(to.getWorld()) &&
                from.getBlockX() == to.getBlockX() &&
                from.getBlockY() == to.getBlockY() &&
                from.getBlockZ() == to.getBlockZ()) {
            return; // did not move
        }
        boolean underBlocks = to.getWorld().getHighestBlockYAt(to) > to.getBlockY() + 1;
        Pl3xMap.api().getPlayerRegistry().optional(event.getPlayer().getUniqueId())
                .ifPresent(player -> player.setHidden(underBlocks, false));
    }

    @EventHandler
    public void onPlayerSneak(PlayerToggleSneakEvent event) {
        if (!getConfig().getBoolean("hide-if-sneaking")) {
            return; // feature disabled
        }
        Pl3xMap.api().getPlayerRegistry().optional(event.getPlayer().getUniqueId())
                .ifPresent(player -> player.setHidden(event.isSneaking(), false));
    }
```

**Comment by 42Willow** [comment]
Thanks time to <del>learn java</del> use github copilot

I'll work on this.

**Comment by JasperTheMinecraftDev** [comment]
> Thanks time to ~learn java~ use github copilot
> 
> I'll work on this.

That's a lazy method of doing it😛
But hey, instead of relying solely on GitHub Copilot, why not dive into learning Java yourself?
Trust me, AI can be a little mischievous at times and might lead you down a confusing path. 
Let's come together and conquer Java by truly understanding it, making mistakes, and learning from them. United we stand, united we learn Java like true champions! 😄🚀
 
 (I'm not only kidding here, you should seriously learn java.)

**Comment by 42Willow** [comment]
> > Thanks time to ~learn java~ use github copilot
> > I'll work on this.
> 
> That's a lazy method of doing it😛 But hey, instead of relying solely on GitHub Copilot, why not dive into learning Java yourself? Trust me, AI can be a little mischievous at times and might lead you down a confusing path. Let's come together and conquer Java by truly understanding it, making mistakes, and learning from them. United we stand, united we learn Java like true champions! 😄🚀
> 
> (I'm not only kidding here, you should seriously learn java.)

I'll try it :)
