### ISSUE TITLE
How to allow access to the web map only to certain IP addresses?

### ISSUE THREAD

**Issue by DimonKoT** [BillyGalbreath/Pl3xMap#179]
I need only certain ip addresses to have access to the web map site. Are there any ways to do this?

**Comment by BillyGalbreath** [comment]
Not with the internal web server. The internal webserver is just a simple "as basic as it gets" web server to help people get up and running quickly. If you require more than it offers you will need to use an external web server or a reverse proxy which provides the functionality you require.
