### ISSUE TITLE
Webp

### ISSUE THREAD

**Issue by jacklollz2** [BillyGalbreath/Pl3xMap#182]
I'd prefer if images could be saved in the efficient Webp format, with configurable quality levels.

**Comment by JasperTheMinecraftDev** [comment]
It's removed afaik because the quality is bad and the weight will be even more than PNG's so there's no benefit.
There is a setting to configure the compression amount.

**Comment by jacklollz2** [comment]
I'm sorry? The quality is bad?
Webp can be stored as lossless, just like PNG.
Webp looks and compresses better than JPEG.
Webp is literally "web png".
WebP lossless images are 26% smaller in size compared to PNGs.
https://developers.google.com/speed/webp/

**Comment by BillyGalbreath** [comment]
You are free to bring back the webp addon from last year. I was never able to make it look decent without bloating the file sizes beyond png, which is why I dropped it in v3.

**Comment by jacklollz2** [comment]
> You are free to bring back the [webp addon](https://github.com/BillyGalbreath/Pl3xMap/tree/v2/addons/webp) from last year. I was never able to make it look decent without bloating the file sizes beyond png, which is why I dropped it in v3.

I've tried many methods, it's impossible for me to get a Lossless WebP to be larger than a Lossless PNG.
I don't know what you're doing.

**Comment by BillyGalbreath** [comment]
Have you tried specifically with the webp library everyone uses for java? I dont care what other methods you're trying. None of them are relevant to this java project.

To be exact, this is the library I am referring to (https://github.com/sksamuel/scrimage), which is a wrapper for the google binaries (https://github.com/sksamuel/scrimage/tree/master/scrimage-webp/src/main/resources/dist_webp_binaries).

If you can honestly get the results you are expecting using this java library (or any other java library), I'd love to see it in a working PR here for me to test. I wont turn away a good thing, but I'm not going to spend any more of my own time on this.
