### ISSUE TITLE
html resets after reload/restart

### ISSUE THREAD

**Issue by DubblePumper** [BillyGalbreath/Pl3xMap#188]
the html in index.html resets everytime i reset my server or reload the plugin by command which prevents me from adding a custom fav icon etc.

**Comment by Roan-V** [comment]
This is done so that updating the plugin cal also update te index file.
You can disable this by setting `read-only` to true in the config

Just remember to set it to false when updating pl3xmap, otherwise your index.html won't get its new updated contents

**Comment by granny** [comment]
What Roan said
