### ISSUE TITLE
900% tick usage

### ISSUE THREAD

**Issue by ancap-kun** [BillyGalbreath/Pl3xMap#189]
https://timin.gs/?id=85c527e186ed424e8d752919d3206b74#plugins

**Comment by BillyGalbreath** [comment]
Timings is not an accurate measurement of anything. Case in point, at the bottom left, click that "All" button and magically Pl3xMap is using ~8% of tick, not ~900%.

**Comment by ancap-kun** [comment]
Because it cause lag spikes, not stable load. If i hadn't tps drops to 14 with only me online, i wouldn't even use timings.
