### ISSUE TITLE
900% tick usage and 12 tps 

### ISSUE THREAD

**Issue by ancap-kun** [BillyGalbreath/Pl3xMap#190]
https://timin.gs/?id=85c527e186ed424e8d752919d3206b74#plugins

I posted this previously, but you complained on timings and closed issue. I answered, but you, probably, didn't saw it. In fact, pl3xmap loads server very intensive, tps drops to 12, but not stably, only for ten seconds in 5 minutes. Thats why timings showed 8% usage on "all" section and 900% on lag section. With unloaded pl3xmap, server don't lag. 

Please fix, because of this problem I can't use plugin. I switched to pl3xmap due to optimisation, but now should find alternatives.

**Comment by U5B** [comment]
It might be more informative if you were able to get a spark report. Timings isnt the most accurate.
https://spark.lucko.me/docs/guides/Finding-lag-spikes
You can use `/spark profiler --only-ticks-over 100` to find lag spikes that take more than two ticks (100ms) to execute

**Comment by granny** [comment]
> Timings is not an accurate measurement of anything
